services:
  presentor-vue:
    build:
      context: ./presentor-vue
      args:
        - VITE_ZONOS_API_URL=http://localhost:8001
        - VITE_MEMO_API_URL=http://localhost:8002
    container_name: presentor-vue
    ports:
      - "80:80"
    networks:
      - web

  zonos-api:
    build:
      context: ./zonos-api
    container_name: zonos-api
    ports:
      - "8001:8000"
    networks:
      - web
    # activate if you have enough VRAM (20 GB were not enough for me)
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  memo-api:
    build:
      context: ./memo-api
    container_name: memo-api
    ports:
      - "8002:8000"
    networks:
      - web
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

networks:
  web:
    driver: bridge
