services:
  zonos-api:
    build:
      context: ./zonos-api
    container_name: zonos-api
    ports:
      - "8001:8000"
    networks:
      - web
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  memo-api:
    build:
      context: ./memo-api
    container_name: memo-api
    ports:
      - "8002:8000"
    networks:
      - web
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

networks:
  web:
    driver: bridge
